
SELECT ?school_lat ?school_long ?data_lat ?data_long ?strength
WHERE{
  ?school <http://data.ordnancesurvey.co.uk/ontology/postcode/postcode> ?pc.
  ?pc <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?school_lat.
  ?pc <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?school_long.
  ?zone <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?data_lat.
  ?zone <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?data_long.
  ?nop <http://data.opendatascotland.org/def/education/numberOfPupils> ?strength.
  ?nop <http://data.opendatascotland.org/def/statistical-dimensions/education/school> ?school.
  ?nop <http://data.opendatascotland.org/def/statistical-dimensions/refArea> ?zone.
}

# Filter by school type add:

  ?school <http://data.opendatascotland.org/def/education/department> ?dep.
  ?dep <http://data.opendatascotland.org/def/education/stageOfEducation> <TYPE>.

where TYPE is one of http://data.opendatascotland.org/def/concept/education/stages-of-education/primary, http://data.opendatascotland.org/def/concept/education/stages-of-education/special, http://data.opendatascotland.org/def/concept/education/stages-of-education/pre-school, http://data.opendatascotland.org/def/concept/education/stages-of-education/secondary
